
[ -f $HOME/.localrc ] && . $HOME/.localrc
export PATH=$HOME/neovim/bin:$PATH
complete -C '$HOME/.local/bin/aws_completer' aws
export PATH=$HOME/.cargo/bin:$PATH
export JAVA_HOME=$HOME/.local/jdk-21.jdk/Contents/Home
export PATH=$JAVA_HOME/bin:$PATH
export PATH=$HOME/.local/apache-maven-3.9.4/bin:$PATH
export PYENV_ROOT=$HOME/.pyenv
export PATH=$PYENV_ROOT/bin:$PATH
eval "$($HOME/.pyenv/bin/pyenv init -)"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH=$HOME/personal/pde-pulumi/_dotfiles/npm/node_modules/.bin:$PATH