export ENHANCD_COMPLETION_BEHAVIOR=list
export ENHANCD_FILTER=fzf
export GOPRIVATE=github.com/corymhall
export JAVA_HOME=/opt/homebrew/opt/openjdk@11
export KEYTIMEOUT=1
export NODE_OPTIONS="--max-old-space-size=8196 --experimental-worker $${NODE_OPTIONS:-}"
export PYENV_ROOT=$HOME/.pyenv
export SHELL=/bin/zsh
export ZINIT_HOME=$HOME/.zinit
export PATH=/Users/chall/.dotnet:$PATH
export PATH=/opt/homebrew/opt/openjdk@11/bin:$PATH
export PATH=/Users/chall/.local/bin:$PATH
export PATH=$HOME/neovim/bin:$PATH
export PATH=$PYENV_ROOT/bin:$PATH
export PATH=/Users/chall/personal/pde/_dotfiles/npm/node_modules/.bin:$PATH
eval "$($HOME/.pyenv/bin/pyenv init -)"
complete -C '$HOME/.local/bin/aws_completer' aws
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[ -f $HOME/.localrc ] && . $HOME/.localrc